[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth

phone_number="+1 911"
api_id=0000000
api_hash="00000000000000000000000000000000"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=0
loop_interval=5